batch_size: 10
gradient_accumulation_steps: 1
lr: 3.0e-4
warm_up: 0.01
bmt_cpu_offload: False
bmt_pre_load: True
save_interval: 10
log_interval: 1
epochs: 10
bmt_loss_scale: 131072
save_optim: True
save_rng: True
eps: 1.e-8