batch_size: 4
gradient_accumulation_steps: 4
lr: 1.0e-4
warm_up: 0.01
epochs: 10
log_interval: 2
eval_interval: 50
save_interval: 200
bmt_cpu_offload: False
bmt_pre_load: True

save_optim: False
save_rng: False
lora: False
enable_sft_dataset_dir: './data/'
enable_sft_dataset_file: 'sft_entitycount.jsonl'
enable_sft_dataset_val_file: 'sft_entitycount_val.jsonl'